version: '3.1'

services:
  mysql:
    image: yilinnyu/project:mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apartmentDB
    ports:
      - "3306:3306"
    networks:
      - docker_network


  react:
    image: yilinnyu/project:react
    container_name: react-container
    ports:
      - "3000:3000"
    networks:
      - docker_network

  springboot:
    image: yilinnyu/project:springboot
    container_name: springboot-container
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - REACT_HOST=react-container
    ports:
      - "8080:8080"
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge