version: '3.1'

services:
  mysql:
    image: yilinnyu/mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apartmentDB
    ports:
      - "3306:3306"

  springboot:
    image: yilinnyu/springboot
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    ports:
      - "8080:8080"
